import React from 'react';
import { Calendar, MapPin, Download, RefreshCw } from '../icons';
import { downloadTeamFixturePDF } from '../../utils/exports';
import SitePlanModal from './SitePlanModal';
import TeamSearch from './TeamSearch';
import TeamDetail from './TeamDetail';
import FixtureList from './FixtureList';

export default function PublicView(props) {
  const { current, upcoming, allFixtures, outsideSchedule } = props.getCurrentAndNext();
  const teamFixtures = props.selectedTeam ? props.getTeamFixtures(props.selectedTeam.id) : [];

  return (
    <div className="min-h-screen bg-gradient-to-b from-green-50 to-white">
      <div className="bg-[#7c1229] text-white p-4 sticky top-0 z-10 shadow-lg">
        <div className="max-w-2xl mx-auto">
          <div className="flex items-center justify-between mb-3">
            <h1 className="text-2xl font-bold">U7's Waterfall</h1>
            <button onClick={() => props.setShowSitePlan(true)} className="flex items-center gap-1.5 bg-white/20 hover:bg-white/30 px-3 py-1.5 rounded-lg transition-colors text-sm font-medium" aria-label="View site plan">
              <MapPin size={18} />
              <span>Site Map</span>
            </button>
          </div>
          {props.selectedTeam ? (
            <div className="flex items-center justify-between">
              <button onClick={() => props.setSelectedTeam(null)} className="text-white/90 hover:text-white font-medium text-sm">{'\u2190'} Back to all fixtures</button>
              <button onClick={() => downloadTeamFixturePDF(props.selectedTeam, props.fixtures, props.setPdfLoading)} disabled={props.pdfLoading} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition-colors text-sm font-medium ${props.pdfLoading ? 'bg-white/10 cursor-wait' : 'bg-white/20 hover:bg-white/30'}`}>
                {props.pdfLoading ? <RefreshCw size={16} className="animate-spin" /> : <Download size={16} />}
                <span>{props.pdfLoading ? 'Generating...' : 'Download PDF'}</span>
              </button>
            </div>
          ) : (
            <TeamSearch
              searchTerm={props.searchTerm}
              setSearchTerm={props.setSearchTerm}
              filteredTeams={props.filteredTeams}
              setSelectedTeam={props.setSelectedTeam}
            />
          )}
        </div>
      </div>
      <SitePlanModal
        showSitePlan={props.showSitePlan}
        setShowSitePlan={props.setShowSitePlan}
        sitePlanZoom={props.sitePlanZoom}
        setSitePlanZoom={props.setSitePlanZoom}
      />
      <div className="max-w-2xl mx-auto p-4 pb-24">
        {props.fixtures.length === 0 ? (
          <div className="bg-white rounded-lg shadow-lg p-8 text-center">
            <Calendar size={48} className="mx-auto text-gray-400 mb-4" />
            <h2 className="text-xl font-bold text-gray-900 mb-2">No Fixtures Yet</h2>
            <p className="text-gray-600">Fixtures will appear here once generated by the admin.</p>
          </div>
        ) : props.selectedTeam ? (
          <TeamDetail
            selectedTeam={props.selectedTeam}
            teamFixtures={teamFixtures}
            fixtures={props.fixtures}
            zones={props.zones}
          />
        ) : (
          <FixtureList
            current={current}
            upcoming={upcoming}
            allFixtures={allFixtures}
            outsideSchedule={outsideSchedule}
          />
        )}
      </div>
    </div>
  );
}
